### ISSUE TITLE
No such file or directory: '../kitti_format/data/kitti/annotations/kitti_val.json'

### ISSUE THREAD

**Issue by DMing11** [Banconxuan/RTM3D#12]
**Hello** @Banconxuan 
**I got an error when I ran your code**：python ./src/main.py --data_dir ./kitti_format --exp_id KM3D_res18 --arch res_18 --batch_size 32 --master_batch_size 16 --lr 1.25e-4 --gpus 0,1 --num_epochs 200

**error:** 
Traceback (most recent call last):
  File "/media/dming/data/RTM3D/src/main.py", line 113, in <module>
    main(opt)
  File "/media/dming/data/RTM3D/src/main.py", line 49, in main
    Dataset(opt, 'val'), 
  File "/media/dming/data/RTM3D/src/lib/datasets/dataset/kittihp.py", line 57, in __init__
    self.coco = coco.COCO(self.annot_path)
  File "/home/dming/anaconda3/envs/RTM3D/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../kitti_format/data/kitti/annotations/kitti_val.json'

**I want to know Where did the annotation folder come from？As far as I know, there is no such directory on Kitti's official website**

**Many thanks!**

**Comment by Banconxuan** [comment]
run 'python src/tools/kitti.py' to generate coco format annotations

**Comment by DMing11** [comment]
many thanks!
