### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'batch'

### ISSUE THREAD

**Issue by DMing11** [Banconxuan/RTM3D#13]
**Hello** @Banconxuan 
There was no problem in the training phase, but an error occurred in the validation phase when I run "python ./src/main.py --data_dir ./kitti_format --exp_id KM3D_res18 --arch res_18 --batch_size 32 --master_batch_size 16 --lr 1.25e-4 --gpus 0,1 --num_epochs 200" ,
3D detection/KM3D_res18Traceback (most recent call last):
  File "./src/main.py", line 113, in <module>
    main(opt)
  File "./src/main.py", line 83, in main
    log_dict_val, preds = trainer.val(epoch, val_loader)
  File "/l4disk/datasets/zhangliming/RTM3D/src/lib/trains/base_trainer.py", line 159, in val
    return self.run_epoch('val', epoch, data_loader)
  File "/l4disk/datasets/zhangliming/RTM3D/src/lib/trains/base_trainer.py", line 97, in run_epoch
    output, loss, loss_stats = model_with_loss(batch,phase=phase)
  File "/home/l4/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/l4/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/l4/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/l4/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/l4/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/l4/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/l4/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'batch'

**No error when I train using one GPU

**what should be wrong?  my pytorch=1.4 
many thank!**

**Comment by yesjames4231-hun** [comment]
I have same problem

**Comment by hao-pt** [comment]
I met this error but we can solve it by uncommenting some codes in `base_trainer.py` from line 75-76:  
      ```
      if len(self.opt.gpus) > 1:
        model_with_loss = self.model_with_loss.module
      model_with_loss.eval()
      torch.cuda.empty_cache()
      ```

**Comment by kai4729** [comment]
> 
> 
> I met this error but we can solve it by uncommenting some codes in `base_trainer.py` from line 75-76:
> `if len(self.opt.gpus) > 1: model_with_loss = self.model_with_loss.module model_with_loss.eval() torch.cuda.empty_cache()`

I try it, and meet a new problem, "TypeError: car_pose_decode() missing 1 required positional argument: 'rot'", just like #33

**Comment by v-vietph** [comment]
> I met this error but we can solve it by uncommenting some codes in `base_trainer.py` from line 75-76:
> `if len(self.opt.gpus) > 1: model_with_loss = self.model_with_loss.module model_with_loss.eval() torch.cuda.empty_cache()`

It works like a champ charm mate.
What a god.
