### ISSUE TITLE
python ./src/faster.py --demo ./kitti_format/kitti/val.txt --data_dir ./kitti_format --calib_dir ./kitti_format/data/kitti/calib/ --load_model ./kitti_format/exp/KM3D_res18/Model_rtm3d_epoch_300.pth --gpus 0 --arch res_18

### ISSUE THREAD

**Issue by kwl11556** [Banconxuan/RTM3D#42]
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  ./kitti_format/exp/default
heads {'hm': 3, 'wh': 2, 'hps': 18, 'rot': 8, 'dim': 3, 'prob': 1, 'reg': 2, 'hm_hp': 9, 'hp_offset': 2}
Creating model...
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/god/.cache/torch/checkpoints/resnet18-5c106cde.pth
100.0%
=> loading pretrained model https://download.pytorch.org/models/resnet18-5c106cde.pth
./kitti_format/exp/KM3D_res18/Model_rtm3d_epoch_300.pth
Traceback (most recent call last):
  File "./src/faster.py", line 55, in <module>
    demo(opt)
  File "./src/faster.py", line 23, in demo
    detector = Detector(opt)
  File "/home/god/KM3D/src/lib/detectors/car_pose.py", line 29, in __init__
    super(CarPoseDetector, self).__init__(opt)
  File "/home/god/KM3D/src/lib/detectors/base_detector.py", line 25, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "/home/god/KM3D/src/lib/models/model.py", line 36, in load_model
    print('loaded {}, epoch {}'.format(model_path, checkpoint['epoch']))
KeyError: 'epoch'

**Comment by Dosimz** [comment]
I think you did not download the correct pretrained models.

You can find the provided model on README.md >> KM3D Baseline and Model Zoo


--------------------------
    Backbone: ResNet-18
    FPS: 46.7
    Model: (Google Drive), (Baidu Cloud 提取码：60ks)
> https://drive.google.com/file/d/14ww6mxtitO9aDszZN3ai8N7U1doehvi8/view?usp=sharing
--------------------------

`python ./src/faster.py --vis --demo ./demo_kitti_format/data/kitti/image --calib_dir ./demo_kitti_format/data/kitti/calib/ --load_model ./demo_kitti_format/exp/KM3D/model_res18_1.pth --gpus 0 --arch res_18`

**Comment by benzg500** [comment]
i have the same problem. i test 4 models provided in readme.md.

**Comment by Takugo** [comment]
I got similar issues. The program just hang there and print nothing after "loaded xxx.pth"
